sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t sunlee/multi-docker-example -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true sunlee/multi-docker-example npm test -- --coverage

after_sucess: 
  - docker build -t sunlee/multi-client ./client
  - docker build -t sunlee/multi-nginx ./nginx
  - docker build -t sunlee/multi-server ./server
  - docker build -t sunlee/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- pasword-stdin
  - docker push sunlee/multi-client
  - docker push sunlee/multi-nginx
  - docker push sunlee/multi-server
  - docker push sunlee/multi-worker